//package org.neo4j.cypher.internal.javacompat;
//
///** Generated by org.neo4j.codegen.source.SourceCodeGenerator */
//public class GeneratedExecutionPlan214986868200137Execution extends java.lang.Object
//        implements org.neo4j.cypher.internal.compiled_runtime.v3_2.executionplan.GeneratedQueryExecution
//{
//    private static final java.util.List<java.lang.String> COLUMNS =
//            java.util.Arrays.asList( new java.lang.String[]{"n"} );
//    public org.neo4j.cypher.internal.compiler.v3_2.TaskCloser closer;
//    public org.neo4j.kernel.api.ReadOperations ro;
//    public org.neo4j.kernel.impl.core.NodeManager nodeManager;
//    public org.neo4j.cypher.internal.compiler.v3_2.ExecutionMode executionMode;
//    public org.neo4j.cypher.internal.compiler.v3_2.executionplan.Provider<org.neo4j.cypher.internal.compiler.v3_2.planDescription.InternalPlanDescription>
//
//            description;
//    public org.neo4j.cypher.internal.compiled_runtime.v3_2.codegen.QueryExecutionTracer tracer;
//    public java.util.Map<java.lang.String,java.lang.Object> params;
//    public org.neo4j.cypher.internal.compiler.v3_2.executionplan.Completable closeable;
//    public org.neo4j.cypher.internal.compiler.v3_2.spi.QueryContext queryContext;
//    public static org.neo4j.cypher.internal.compiler.v3_2.planDescription.Id OP1_ProduceResult;
//    public static org.neo4j.cypher.internal.compiler.v3_2.planDescription.Id OP2_NodeByLabelScan;
//
//    public GeneratedExecutionPlan214986868200137Execution( org.neo4j.cypher.internal.compiler.v3_2.TaskCloser closer,
//            org.neo4j.cypher.internal.compiler.v3_2.spi.QueryContext queryContext,
//            org.neo4j.cypher.internal.compiler.v3_2.ExecutionMode executionMode,
//            org.neo4j.cypher.internal.compiler.v3_2.executionplan.Provider<org.neo4j.cypher.internal.compiler.v3_2.planDescription.InternalPlanDescription> description,
//            org.neo4j.cypher.internal.compiled_runtime.v3_2.codegen.QueryExecutionTracer tracer,
//            java.util.Map<java.lang.String,java.lang.Object> params )
//    {
//        super();
//        this.closer = closer;
//        this.queryContext = queryContext;
//        this.executionMode = executionMode;
//        this.description = description;
//        this.tracer = tracer;
//        this.params = params;
//        this.nodeManager = ((org.neo4j.kernel.impl.core.NodeManager) queryContext.entityAccessor());
//    }
//
//    public org.neo4j.kernel.api.ReadOperations getOrLoadReadOperations()
//    {
//        if ( this.ro == null )
//        {
//            this.ro = ((org.neo4j.kernel.api.ReadOperations) this.queryContext.transactionalContext().readOperations());
//        }
//        return this.ro;
//    }
//
//    public void setSuccessfulCloseable( org.neo4j.cypher.internal.compiler.v3_2.executionplan.Completable closeable )
//    {
//        this.closeable = closeable;
//    }
//
//    public org.neo4j.cypher.internal.compiler.v3_2.ExecutionMode executionMode()
//    {
//        return this.executionMode;
//    }
//
//    public org.neo4j.cypher.internal.compiler.v3_2.planDescription.InternalPlanDescription executionPlanDescription()
//    {
//        return ((org.neo4j.cypher.internal.compiler.v3_2.planDescription.InternalPlanDescription) this.description
//                .get());
//    }
//
//    public java.util.List<java.lang.String> javaColumns()
//    {
//        return org.neo4j.cypher.internal.compiler.v3_2.generated.GeneratedExecutionPlan214986868200137Execution.COLUMNS;
//    }
//
//    public <E extends java.lang.Exception> void accept(
//            org.neo4j.cypher.internal.compiler.v3_2.spi.InternalResultVisitor<E> visitor ) throws E
//    {
//        org.neo4j.cypher.internal.compiler.v3_2.ResultRowImpl row =
//                new org.neo4j.cypher.internal.compiler.v3_2.ResultRowImpl();
//        int v2 = this.getOrLoadReadOperations().labelGetForName( "Label" );
//        org.neo4j.cypher.internal.compiled_runtime.v3_2.codegen.QueryExecutionEvent event_OP2_NodeByLabelScan =
//                this.tracer.executeOperator(
//                        org.neo4j.cypher.internal.compiler.v3_2.generated.GeneratedExecutionPlan214986868200137Execution.OP2_NodeByLabelScan );
//        org.neo4j.collection.primitive.PrimitiveLongIterator v1Iter =
//                this.getOrLoadReadOperations().nodesGetForLabel( v2 );
//        event_OP2_NodeByLabelScan.dbHit();
//        while ( v1Iter.hasNext() )
//        {
//            event_OP2_NodeByLabelScan.row();
//            event_OP2_NodeByLabelScan.dbHit();
//            long v1 = v1Iter.next();
//            org.neo4j.cypher.internal.compiled_runtime.v3_2.codegen.QueryExecutionEvent event_OP1_ProduceResult =
//                    this.tracer.executeOperator(
//                            org.neo4j.cypher.internal.compiler.v3_2.generated.GeneratedExecutionPlan214986868200137Execution.OP1_ProduceResult );
//            event_OP1_ProduceResult.row();
//            row.set( "n", this.nodeManager.newNodeProxyById( v1 ) );
//            try
//            {
//                if ( !(visitor.visit( row )) )
//                {
//                    event_OP1_ProduceResult.close();
//                    event_OP2_NodeByLabelScan.close();
//                    this.closeable.completed( true );
//                    return;
//                }
//            }
//            catch ( java.lang.Throwable e )
//            {
//                event_OP1_ProduceResult.close();
//                event_OP2_NodeByLabelScan.close();
//                this.closeable.completed( false );
//                throw e;
//            }
//            event_OP1_ProduceResult.close();
//        }
//        event_OP2_NodeByLabelScan.close();
//        this.closeable.completed( true );
//    }
//}
