//package org.neo4j.cypher.internal.javacompat;
///** Generated by org.neo4j.codegen.source.SourceCodeGenerator */
//public class GeneratedExecutionPlan215257648930353 extends java.lang.Object
//        implements org.neo4j.cypher.internal.compiled_runtime.v3_2.executionplan.GeneratedQuery
//{
//    public org.neo4j.cypher.internal.compiled_runtime.v3_2.executionplan.GeneratedQueryExecution execute(
//            org.neo4j.cypher.internal.compiler.v3_2.TaskCloser closer,
//            org.neo4j.cypher.internal.compiler.v3_2.spi.QueryContext queryContext,
//            org.neo4j.cypher.internal.compiler.v3_2.ExecutionMode executionMode,
//            org.neo4j.cypher.internal.compiler.v3_2.executionplan.Provider<org.neo4j.cypher.internal.compiler.v3_2.planDescription.InternalPlanDescription> description,
//
//            org.neo4j.cypher.internal.compiled_runtime.v3_2.codegen.QueryExecutionTracer tracer,
//            java.util.Map<java.lang.String,java.lang.Object> params )
//    {
//        return new org.neo4j.cypher.internal.compiler.v3_2.generated.GeneratedExecutionPlan215257648930353Execution(
//                closer, queryContext, executionMode, description, tracer, params );
//    }
//
//    public GeneratedExecutionPlan215257648930353()
//    {
//        super();
//    }
//}
